language: go

dist: xenial
sudo: required

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
env:
  - GO111MODULE=on

before_install: go get golang.org/x/tools/cmd/goimports

script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  # - diff -u <(echo -n) <(goimports -d .)
  - go test -v -race ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
