[jupiter.server.http]
    port = 20105
[jupiter.server.grpc]
    port = 20102

[jupiter.etcdv3.default]
    endpoints=["127.0.0.1:2379"]
    secure = false

[jupiter.registry.bj01]
    configKey="jupiter.etcdv3.default"
    timeout = "1s"
[jupiter.registry.bj02]
    configKey="jupiter.etcdv3.default"
    timeout = "1s"
[jupiter.cron.demo]
    immediatelyRun = true
    concurrentDelay = 5
[jupiter.mysql.test]
    connMaxLifetime = "300s"
    debug = true
    dsn = "user:pwd@tcp(127.0.0.1:3306)/test?charset=utf8&parseTime=True&loc=Local"
    level = "panic"
    maxIdleConns = 50
    maxOpenConns = 100
    disableTrace = true
    disableMetric = true
[jupiter.trace.jaeger]
    enableRPCMetrics = false
    [jupiter.trace.jaeger.sampler]
        type = "const"
        param = 0.001