name: e2e-test

on:
  push:
    paths-ignore:
      - "website/**"
    branches:
      - "master"
  pull_request:
    paths-ignore:
      - "website/**"
    branches:
      - "master"

jobs:
  e2e-test:
    name: Test on ubuntu
    strategy:
      fail-fast: true
      matrix:
        go: ["1.19.x"]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: docker-compose
        run: docker-compose -f test/docker-compose.yaml up -d

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Install ginkgo
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@latest
          sudo cp ~/go/bin/ginkgo /usr/local/bin

      - name: Get dependencies
        run: |
          go env
          go mod tidy && git diff --exit-code go.mod go.sum

      - name: E2E test
        run: |
          make e2e-test

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
          files: ./test/e2e/coverage.txt
          name: jupiter-e2e
          verbose: true
