name: unit-test

on:
  push:
    paths-ignore:
      - "website/**"
    branches:
      - "master"
  pull_request_target:
    paths-ignore:
      - "website/**"
    branches:
      - "master"

jobs:
  test:
    name: Test on ubuntu
    environment:
      name: tablestore-live
    env:
      TABLESTORE_ACCESSKEYID_ENV: ${{ secrets.TABLESTORE_ACCESSKEYID_ENV }}
      TABLESTORE_ACCESSKEYSECRET_ENV: ${{ secrets.TABLESTORE_ACCESSKEYSECRET_ENV }}
      TABLESTORE_ENDPOINT_ENV: ${{ secrets.TABLESTORE_ENDPOINT_ENV }}
      TABLESTORE_INSTANCE_ENV: ${{ secrets.TABLESTORE_INSTANCE_ENV }}
    strategy:
      fail-fast: true
      matrix:
        go: ["1.19.x"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: docker-compose
        run: docker-compose -f test/docker-compose.yaml up -d

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Get dependencies
        run: |
          go env
          go mod tidy && git diff --exit-code go.mod go.sum

      - name: Test
        run: |
          make unit-test

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
          files: ./coverage.txt
          name: jupiter
          verbose: true
